version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.4
  win: circleci/windows@2.2.0

jobs:
  build:
    working_directory: ~/shopware-pwa
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: yarn --frozen-lockfile
      - run:
          name: test
          command: yarn test:coverage --w 2
      - coveralls/upload
      - persist_to_workspace:
          root: ~/shopware-pwa
          paths:
            - ./*
  test:
    executor: win/default
    working_directory: ~/shopware-pwa
    steps:
      - attach_workspace:
          at: ~/shopware-pwa
      - run:
          name: coverage
          command: yarn test:coverage --w 2


workflows:
  version: 2
  build-test:
    jobs:
    - build
    - test:
        requires:
        - build