name: E2E Cypress tests

on:
  push:
    branches:
      # - e2e
      - master
  pull_request: # temp for tests
    types: [opened, synchronize]

jobs:

  test:
    name: Cypress tests
    needs: init
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache node_modules
        if: steps.step-cache-build.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-test
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: yarn test e2e
        run: |
          yarn --frozen-lockfile
          yarn test:cypress --config baseUrl=https://shopware-pwa-canary.storefrontcloud.io/
        env:
          CI: true
