name: E2E Cypress tests

on:
  push:
    branches:
      # - e2e
      - master
  pull_request: # temp for tests
    types: [opened, synchronize]

jobs:
  test:
    name: Cypress tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: yarn test e2e
        run: |
          npm i -g yarn
          yarn
          yarn test:cypress --config baseUrl=https://shopware-pwa-canary.storefrontcloud.io/
        env:
          CI: true
